### ISSUE TITLE
It wont generate the pdf file

### ISSUE THREAD

**Issue by vinoth786** [satyendra-singh-talentica/node-pdf#1]
{ Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1173:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }

**Comment by felipe-alecsandro** [comment]
I have some problem.

**Comment by vinoth786** [comment]
what is the  problem  ??

**Comment by felipe-alecsandro** [comment]
Sorry. I meant the "same" problem.
"ERROR in PDF generation : Error: connect ECONNREFUSED 127.0.0.1:9222"

**Comment by felipe-alecsandro** [comment]
It worked for me now. I just reinstalled the node.

Tks.

**Comment by vinoth786** [comment]
ok

**Comment by vinoth786** [comment]
https://github.com/4idlm/pdf-generation-firebase


you can try this code

**Comment by ssxv** [comment]
{ Error: connect ECONNREFUSED 127.0.0.1:9222
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1173:14)
errno: 'ECONNREFUSED',
code: 'ECONNREFUSED',
syscall: 'connect',
address: '127.0.0.1',
port: 9222 }

looks like you already have chrome running on port 9222, fix that and this will work
